sonar.projectKey=lab-web-app
sonar.projectName=lab-web-app
sonar.sources=lab-web-app/src
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.qualitygate.wait=true
# For SonarQube Cloud uncomment and set:
sonar.organization=REPLACE_WITH_ORGANIZATION
